server {
        listen 80;
        server_name hcst_api.natelevison.com;
        error_log /var/log/nginx/hcst_api.natelevison.com.error.log;

        location / {
                #add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Cross-Origin-Opener-Policy' 'same-origin-allow-popups' always;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection upgrade;
                proxy_set_header Accept-Encoding gzip;

                proxy_pass http://127.0.0.1:8081;
                proxy_redirect off;
        }
}

server {
        listen 80;
        server_name hcst.natelevison.com;
        error_log /var/log/nginx/hcst.natelevison.com.error.log;

        location / {
                add_header 'Access-Control-Allow-Origin' 'same-origin' always;
                add_header 'Cross-Origin-Opener-Policy' 'same-origin-allow-popups' always;
                proxy_set_header Host $host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection upgrade;
                proxy_set_header Accept-Encoding gzip;

                proxy_pass http://127.0.0.1:8082;
                proxy_redirect off;
        }
}